name: Digtal Ocean - deploy

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_EE }}
        username: ${{ secrets.SSH_USERNAME }}
        ssh: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: whoami
